Make start-vpn more robust
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

diff --git a/start-vpn b/start-vpn
--- a/start-vpn
+++ b/start-vpn
@@ -1,7 +1,7 @@
 #!/bin/sh -eu
 
 ### Usage
-if [ -z "$1" ] || [ -z "$2" ]; then
+if [ -z "${1:-}" ] || [ -z "${2:-}" ]; then
     echo "Usage: ${0} [--opts='openvpn args'] <VPN name> <VPN config> [byobu|tmux]"
     echo " e.g.: ${0}  --opts='--pull dhcp-options --up /etc/openvpn/update-resolv-conf --script-security 2'  ..."
     exit 1
@@ -10,7 +10,7 @@ fi
 ### Argument parsing
 OPENVPN_OPTS=
 OPENVPN_DEFAULT="false"
-case "$1" in
+case "${1}" in
     --opts=*)
         # shellcheck disable=SC2034
         OPENVPN_OPTS="${1#--opts=}"
@@ -25,9 +25,23 @@ esac
 VPN_NAME=${1}
 VPN_CONFIG=${2}
 MULTIPLEXER=${3:-"byobu"}
+WORKDIR="${XDG_RUNTIME_DIR:-~/.cache}/vpn-container"
+[ -d "${WORKDIR}" ] || mkdir -p "${WORKDIR}"
 
 ### Check if already running
-[ ! -e "${VPN_NAME}.sock" ] || (echo "VPN is already running" && exit 1)
+[ ! -e "${WORKDIR}/${VPN_NAME}.sock" ] || (echo "VPN is already running" && exit 1)
+
+### Setup exit cleanup
+cleanup() {
+    set +eu
+
+    # Wait for things to finish
+    wait "${NS_PID}" >/dev/null 2>&1
+
+    kill -9 "${SOCAT_PID}" >/dev/null 2>&1
+    rm -f "${WORKDIR}/${VPN_NAME}.sock" "${WORKDIR}/${VPN_NAME}.sock_in"
+}
+trap cleanup EXIT HUP INT TERM
 
 ### Dependency check
 which socat >/dev/null \
@@ -66,13 +80,13 @@ fi
 case "$VPN_PROTO" in
     tcp|tcp6)
          LPORT=""
-         SOCK_HOST="UNIX-LISTEN:${VPN_NAME}.sock"
-         SOCK_GUEST="UNIX-CLIENT:${VPN_NAME}.sock"
+         SOCK_HOST="UNIX-LISTEN:${WORKDIR}/${VPN_NAME}.sock"
+         SOCK_GUEST="UNIX-CLIENT:${WORKDIR}/${VPN_NAME}.sock"
          ;;
     udp|udp6)
          LPORT="--nobind --float"
-         SOCK_HOST="UNIX-SENDTO:${VPN_NAME}.sock_in,bind=${VPN_NAME}.sock"
-         SOCK_GUEST="UNIX-SENDTO:${VPN_NAME}.sock,bind=${VPN_NAME}.sock_in"
+         SOCK_HOST="UNIX-SENDTO:${WORKDIR}/${VPN_NAME}.sock_in,bind=${WORKDIR}/${VPN_NAME}.sock"
+         SOCK_GUEST="UNIX-SENDTO:${WORKDIR}/${VPN_NAME}.sock,bind=${WORKDIR}/${VPN_NAME}.sock_in"
          ;;
     *)   echo "Only tcp or udp VPNs are supported at this time." >&2
          exit 1
@@ -86,6 +100,12 @@ SOCAT_PID=$!
 ### Exec stage-2
 (
 cat << EOF
+cleanup() {
+    rm -f ${WORKDIR}/${VPN_NAME}.console
+    rm -Rf \$TEMPDIR
+}
+trap cleanup EXIT HUP INT TERM
+
 # Setup proc
 mount -t proc proc /proc
 
@@ -151,17 +171,14 @@ OPENVPN_OPTS="--script-security 2 --up \$TEMPDIR/vpn-up \$OPENVPN_OPTS"
 
 # Start OpenVPN in ${MULTIPLEXER}
 cd "$(dirname "${VPN_CONFIG}")"
-${MULTIPLEXER} -S ${PWD}/${VPN_NAME}.console new-session -n VPN -d \
+${MULTIPLEXER} -S ${WORKDIR}/${VPN_NAME}.console new-session -n VPN -d \
     "openvpn --remote 127.0.0.1 ${VPN_PORT:-"1194"} --config ${VPN_CONFIG} ${LPORT} --user ${USER} --group root \$OPENVPN_OPTS; bash"
 cd $PWD
 
 # Ready
-while ${MULTIPLEXER} -S ${VPN_NAME}.console list-sessions >/dev/null 2>&1; do
+while ${MULTIPLEXER} -S ${WORKDIR}/${VPN_NAME}.console list-sessions >/dev/null 2>&1; do
     sleep 0.5
 done
-
-rm -f ${VPN_NAME}.console
-rm -Rf \$TEMPDIR
 EOF
 ) | lxc-usernsexec -m "u:0:$(id -u):1" -m "g:0:$(id -g):1" -- \
     lxc-unshare -s "NETWORK|MOUNT|UTSNAME|PID" -- /bin/sh &
@@ -169,26 +186,22 @@ NS_PID=$!
 
 # Wait for the namespace to get setup
 timeout=60
-while [ ! -e "${VPN_NAME}.console" ] && [ "${timeout}" -gt "0" ]; do
+while [ ! -e "${WORKDIR}/${VPN_NAME}.console" ] && [ "${timeout}" -gt "0" ]; do
     sleep 0.5
     timeout=$((timeout-1))
 done
 
 if [ "${timeout}" = "0" ]; then
     echo "VPN failed to start" >&2
+    exit 1
 else
     # Attach to session
-    while $MULTIPLEXER -S "${VPN_NAME}.console" list-sessions >/dev/null 2>&1; do
-        $MULTIPLEXER -S "${VPN_NAME}.console" new-window -t 1 -c "$HOME" \
+    while $MULTIPLEXER -S "${WORKDIR}/${VPN_NAME}.console" list-sessions >/dev/null 2>&1; do
+        $MULTIPLEXER -S "${WORKDIR}/${VPN_NAME}.console" new-window -t 1 -c "$HOME" \
             "cat /run/motd.dynamic ; bash"
             >/dev/null 2>&1 || true
-        $MULTIPLEXER -S "${VPN_NAME}.console" attach
+        $MULTIPLEXER -S "${WORKDIR}/${VPN_NAME}.console" attach
     done
 fi
 
-# Wait for things to finish
-wait ${NS_PID}
-
-# Cleanup
-kill -9 ${SOCAT_PID} 2>/dev/null
-rm -f "${VPN_NAME}.sock" "${VPN_NAME}.sock_in"
+exit 0
